export const iconsData = [
  { content: "home-4-line", iconClass: "ri-home-4-line" },
  { content: "home-4-fill", iconClass: "ri-home-4-fill" },
  { content: "arrow-right-line", iconClass: "ri-arrow-right-line" },
  { content: "arrow-left-line", iconClass: "ri-arrow-left-line" },
  { content: "building-line", iconClass: "ri-building-line" },
  { content: "bank-line", iconClass: "ri-bank-line" },
  { content: "mail-line", iconClass: "ri-mail-line" },
  { content: "mail-fill", iconClass: "ri-mail-fill" },
  { content: "cloud-line", iconClass: "ri-cloud-line" },
  { content: "award-line", iconClass: "ri-award-line" },
  { content: "pie-chart-line", iconClass: "ri-pie-chart-line" },
  { content: "briefcase-2-line", iconClass: "ri-briefcase-2-line" },
  { content: "calendar-line", iconClass: "ri-calendar-line" },
  { content: "bookmark-line", iconClass: "ri-bookmark-line" },
  { content: "global-line", iconClass: "ri-global-line" },
  {
    content: "customer-service-2-line",
    iconClass: "ri-customer-service-2-line"
  },
  { content: "printer-line", iconClass: "ri-printer-line" },
  { content: "stack-line", iconClass: "ri-stack-line" },
  {
    content: "question-answer-line",
    iconClass: "ri-question-answer-line"
  },
  { content: "ball-pen-line", iconClass: "ri-ball-pen-line" },
  { content: "brush-2-line", iconClass: "ri-brush-2-line" },
  { content: "scissors-line", iconClass: "ri-scissors-line" },
  { content: "eraser-line", iconClass: "ri-eraser-line" },
  {
    content: "pencil-ruler-2-line",
    iconClass: "ri-pencil-ruler-2-line"
  },
  { content: "tools-line", iconClass: "ri-tools-line" },
  { content: "layout-line", iconClass: "ri-layout-line" },
  { content: "braces-line", iconClass: "ri-braces-line" },
  { content: "phone-line", iconClass: "ri-phone-line" },
  { content: "database-2-line", iconClass: "ri-database-2-line" },
  { content: "save-line", iconClass: "ri-save-line" },
  { content: "airplay-line", iconClass: "ri-airplay-line" },
  { content: "shut-down-line", iconClass: "ri-shut-down-line" },
  { content: "gps-line", iconClass: "ri-gps-line" },
  { content: "file-copy-line", iconClass: "ri-file-copy-line" },
  { content: "file-line", iconClass: "ri-file-line" },
  { content: "file-zip-line", iconClass: "ri-file-zip-line" },
  { content: "folder-2-line", iconClass: "ri-folder-2-line" },
  { content: "wallet-line", iconClass: "ri-wallet-line" },
  { content: "vip-crown-line", iconClass: "ri-vip-crown-line" },
  { content: "trophy-line", iconClass: "ri-trophy-line" },
  { content: "coupon-line", iconClass: "ri-coupon-line" },
  { content: "shopping-bag-line", iconClass: "ri-shopping-bag-line" },
  { content: "gift-line", iconClass: "ri-gift-line" }
];
