import {
  Airplay,
  AlertOctagon,
  AlertTriangle,
  Archive,
  Briefcase,
  Box,
  Boxes,
  CalendarCheck,
  Camera,
  CheckCircle,
  CheckSquare,
  Clock4,
  Contact2,
  Copy,
  Cpu,
  Database,
  Eye,
  Expand,
  FolderClosed,
  Gift,
  Gem,
  GaugeCircle,
  Globe,
  GraduationCap,
  HardDrive,
  Headphones,
  Heart,
  History,
  Home,
  Image,
  Import,
  Inbox,
  KeyRound,
  Laugh,
  Layers,
  LogIn,
  MapPin,
  Mail,
  MessagesSquare,
  Mic,
  PencilRuler,
  BadgeAlert,
  Tag,
  Trash2,
  BellRing
} from "lucide-vue-next";

export const icons = [
  { content: "airplay", icon: Airplay },
  { content: "alert-octagon", icon: AlertOctagon },
  { content: "alert-triangle", icon: AlertTriangle },
  { content: "archive", icon: Archive },
  { content: "briefcase", icon: Briefcase },
  { content: "box", icon: Box },
  { content: "boxes", icon: Boxes },
  { content: "calendar-check", icon: CalendarCheck },
  { content: "camera", icon: Camera },
  { content: "check-circle", icon: CheckCircle },
  { content: "check-square", icon: CheckSquare },
  { content: "clock-4", icon: Clock4 },
  { content: "contact-2", icon: Contact2 },
  { content: "copy", icon: Copy },
  { content: "cpu", icon: Cpu },
  { content: "database", icon: Database },
  { content: "eye", icon: Eye },
  { content: "expand", icon: Expand },
  { content: "folder-closed", icon: FolderClosed },
  { content: "gift", icon: Gift },
  { content: "gem", icon: Gem },
  { content: "gauge-circle", icon: GaugeCircle },
  { content: "globe", icon: Globe },
  { content: "graduation-cap", icon: GraduationCap },
  { content: "hard-drive", icon: HardDrive },
  { content: "headphones", icon: Headphones },
  { content: "heart", icon: Heart },
  { content: "history", icon: History },
  { content: "home", icon: Home },
  { content: "image", icon: Image },
  { content: "import", icon: Import },
  { content: "inbox", icon: Inbox },
  { content: "key-round", icon: KeyRound },
  { content: "laugh", icon: Laugh },
  { content: "layers", icon: Layers },
  { content: "log-in", icon: LogIn },
  { content: "map-pin", icon: MapPin },
  { content: "mail", icon: Mail },
  { content: "messages-square", icon: MessagesSquare },
  { content: "mic", icon: Mic },
  { content: "pencil-ruler", icon: PencilRuler }
];

export const iconData = [
  {
    content: "airplay",
    icon: Airplay,
    animateClass: "animate-icons",
    textColor: "text-slate-500",
    fillColor: "fill-slate-100",
    darkFillColor: "dark:fill-zink-500"
  },
  {
    content: "alert-octagon",
    icon: AlertOctagon,
    animateClass: "animate-icons",
    textColor: "text-custom-500",
    fillColor: "fill-custom-100",
    darkFillColor: "dark:fill-custom-500/20"
  },
  {
    content: "check-circle",
    icon: CheckCircle,
    animateClass: "animate-icons",
    textColor: "text-green-500",
    fillColor: "fill-green-100",
    darkFillColor: "dark:fill-green-500/20"
  },
  {
    content: "badge-alert",
    icon: BadgeAlert,
    animateClass: "animate-icons",
    textColor: "text-orange-500",
    fillColor: "fill-orange-100",
    darkFillColor: "dark:fill-orange-500/20"
  },
  {
    content: "tag",
    icon: Tag,
    animateClass: "animate-icons",
    textColor: "text-sky-500",
    fillColor: "fill-sky-100",
    darkFillColor: "dark:fill-sky-500/20"
  },
  {
    content: "alert-triangle",
    icon: AlertTriangle,
    animateClass: "animate-icons",
    textColor: "text-yellow-500",
    fillColor: "fill-yellow-100",
    darkFillColor: "dark:fill-yellow-500/20"
  },
  {
    content: "trash-2",
    icon: Trash2,
    animateClass: "animate-icons",
    textColor: "text-red-500",
    fillColor: "fill-red-100",
    darkFillColor: "dark:fill-red-500/20"
  },
  {
    content: "bell-ring",
    icon: BellRing,
    animateClass: "animate-icons",
    textColor: "text-purple-500",
    fillColor: "fill-purple-100",
    darkFillColor: "dark:fill-purple-500/20"
  }
];
